### ISSUE TITLE
Actual GUID for newly spawned cards

### ISSUE THREAD

**Issue by MokThePok** [tjakubo2/Decker#3]
Hi tjakubo2,

_First of all:_ Fantastic code and great functionality. Really very helpful. Thank you!

I'm struggling with one thing though, and that might very well be on my end. But I'm stuck and hope you can help me out or explain this.

I'm trying to get the GUID for newly spawned cards (e.g. five separate cards). 
I know that the default in your script is deadbf and that I can assign a GUID myself in the Decker.Card function.
I'm still wondering if there is really no "easy" way to get the GUID after calling the spawn function for multiple objects?

If there isn't, I'd probably write a function to generate a GUID that doesn't exist yet and passes it on. Thought I'd give contacting you here a shot first though.

Thanks!

**Comment by tjakubo2** [comment]
Hey, like you mentioned, TTS doesn't really respect the GUIDs you try to set - I just put 'deadbf' there because then TTS simply assigns a valid unique GUID after spawning.

You *could* set your own GUID and rely on that, but aside from this, you'd have to wait for the card/deck to finish spawning and then read its GUID. You can achieve that with e.g. Wait.condition, like
```lua
local deck = deckerDeckObject:spawn({position = Vector(1, 2, 3)})
Wait.condition(
    function()
        print('assigned guid is ' .. deck.getGUID())
    end,
    function()
        return not deck.spawning
    end
)
```

But the real question IMO is - why do you need the GUIDs immediately after spawn? If you'd want to keep a reference to the deck in somewhere to use it later, you can just keep the ``deck`` variable returned by ``DeckerObject:spawn(params)``. It's only when saving the thing persistently, you need to save GUIDs :)

**Comment by MokThePok** [comment]
Hey, thanks for the quick reply.
Looks like I at least didn't overlook anything major. :)

Also thanks for adding the comment about the Wait.condition. This one I was aware of. 

And yes, it's exactly for the purpose of saving.
I'll probably just give the cards a unique name and go through all objects when saving.
